version: "3"
services:
  shiny:
    build: ./shiny
    ports:
      - "3838:3838"
    volumes:
      - ./shiny_app:/srv/shiny-server
      - ./scripts:/scripts
      - ./data:/data
      
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888" # Map Jupyter notebook port
    volumes:
       - ./data:/home/user/data
       - ./scripts:/home/user/scripts
       - ./notebooks:/home/user/notebooks
