version: "3"
services:
  shiny:
    build: ./shiny
    ports:
      - "3838:3838"
    volumes:
      - ./app:/srv/shiny-server
      - ./scripts:/srv/shiny-server/scripts
      - ./app/www/data:/srv/shiny-server/www/data
      - ./app/www/figures:/srv/shiny-server/www/figures
      
  jupyter:
    build:
      context: ./jupyter
    ports:
      - "8888:8888" # Map Jupyter notebook port
    volumes:
       - ./app:/home/user/app
       - ./data:/home/user/data
       - ./scripts:/home/user/scripts
       - ./notebooks:/home/user/notebooks
       - ./figures:/home/user/figures
